### ISSUE TITLE
Choose one or more databases

### ISSUE THREAD

**Issue by yorkshirelandscape** [MikhailProfile/SearchEverywhere#1]
Hi Mikhail! Thanks for creating this. It's already an improvement over Redgate's offering in that it's better integrated into ADS. Unfortunately, it suffers from the same problem theirs does in that you can't select a database (or multiple databases) in which to search.  So I'm stuck only searching the `master` database unless I create a new connection with a different database as the default. 

Do you think that's something you could make happen?

**Comment by MikhailProfile** [comment]
Hey Andrew,

That's something that I'm thinking too. Because for now it's not really obvious which database is active for the extension.  

Maybe some new shortcut that allow to choose active connection before searching. 
I will try to take a look into it.

**Comment by MikhailProfile** [comment]
Hey Andrew,

I have fixed a bug with changing database inside one connection. You could try it in the new release 1.1.
