### ISSUE TITLE
Additional open options for Objects

### ISSUE THREAD

**Issue by manthena** [MikhailProfile/SearchEverywhere#5]
Hi @MikhailProfile,

This has been a really helpful extension. 

Quick feature requests if they are feasible. 

As of now, when I select a stored procedure, it opens the ALTER view. It would be great if there was an additional option to open an EXECUTE statement along with sp parameters declared.

For Table objects, as of now, the tool opens a new window with SELECT TOP 1000. It would be great if there is an additional option to open the Azure Data Studio Design View. 

For View objects, it would be helpful if there is an additional option for opening ALTER statement.

Thanks,
Aditya

**Comment by MikhailProfile** [comment]
Hey!

Nice suggestion. I will try to include it in a new version.

**Comment by MikhailProfile** [comment]
Hey,

You could try to use this version:

https://github.com/MikhailProfile/SearchEverywhere/releases/tag/1.2.1
