### ISSUE TITLE
Search by field name and return table name

### ISSUE THREAD

**Issue by gregclerk** [MikhailProfile/SearchEverywhere#7]
Nice extension!

Right now when I type in a field name it doesn't return the table(s) to which that field belongs.  Is that a known issue?

Thanks!

**Comment by MikhailProfile** [comment]
Hey Greg,

I'm glad that you found it useful! 

You could find checkbox "Add columns information to Tables" in extension settings. 

<img width="650" alt="image" src="https://github.com/user-attachments/assets/9b4d339e-ea59-4901-a575-dd85202adeb2">

<img width="540" alt="image" src="https://github.com/user-attachments/assets/7199060c-f5fa-411b-bdf9-1b79ffa66a93">
